### ISSUE TITLE
Create ROS skeleton according to ROS architecture

### ISSUE THREAD

**Issue by nlitz88** [klammecr/f1tenth-project#1]
Based on the ROS architecture that we start with, stub out the nodes, launch files, and configuration files needed.

https://drive.google.com/file/d/1BATDyWmKOQUToBIlDpQCdGi3wdpDM5Lv/view?usp=drive_link

**Comment by nlitz88** [comment]
@CMUBOB97 @klammecr (does Tianhao not have access to the project repo? Can't tag him here):

While I know we specified how we want to divide up the ROS nodes in the diagram, we didn't discuss whether these nodes should all be in the same package or separate packages.

I.e., we probably don't want Chi's RRT node as a part of this package, but it should rather be a dependency (I.e., the planning component is kind of out of scope). **We can** just dump his RRT node in here for the sake of the project--but I wanted your two cents if we think it's worth doing it the "more correct way" and keeping it in a separate package (and perhaps meaning its own repository then, too).

If the more "politically correct" way I'm describing above sounds like too much headache, then we can proceed with just creating all the nodes as a part of this package alone.

**Comment by klammecr** [comment]
Maybe he did not accept the invite yet

**Comment by klammecr** [comment]
We can probably add Chi's RRT node as a submodule if possible and is standalone
